### ISSUE TITLE
Feature: User can create a game room

### ISSUE THREAD

**Issue by ry-zhao** [ry-zhao/kalah-io#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a game room.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can create a game room by clicking the plus button on the lower app bar. Once the room is created, it will be displayed in the lobby.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/88162193/140583858-ab9b3ab6-0aa2-4bcb-93ca-bf54cb29c524.png)
![image](https://user-images.githubusercontent.com/88162193/140984505-43fd159c-7472-40c0-9f28-14c34531d462.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create function that issues an SQL query for all rooms stored in the DB upon server startup
- [x] Create object to store and manage rooms
- [x] Create a middleware that sends a list of all active rooms when clients access the "lobby" screen
- [x] Create middleware to create a new room when client sends request to do so
  - [x] Add callback so that server issues SQL query to insert new room into "gamesRooms" table
  - [x] Add callback so that server sends new room data to all clients currently on the lobby screen

### ⚡ Client

- [x] Create an "add room" button component in lower app bar
- [x] Create event handler on the button so that a modal for creating a new room appears upon click
- [x] Add an event listener on the modal's form so that the socket sends a request to the server to create a new room and closes the modal upon click
- [x] Create an event handler that renders cards for each room in the lobby screen
- [x] Ensure desktop compatibility

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
